name: "Tests"
on:
  push:
  pull_request:
jobs:
  nix-instantiate:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: workflow/nix-shell-action@v1
        with:
          script: |
            cabal install base-4.13.0.0
            cabal build
      - name: test
        run: |
          cabal test 